#!/usr/bin/env bash
# Record exact versions of HF-critical packages after a successful verify run.
# Commit constraints/venv-lock-hf.txt when intentionally upgrading the stack.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PIP="${ROOT}/venv/bin/pip"
OUT="${ROOT}/constraints/venv-lock-hf.txt"
mkdir -p "${ROOT}/constraints"

pkgs=(transformers huggingface_hub tokenizers safetensors diffusers peft accelerate torch torchvision)
{
  echo "# Auto-generated by scripts/snapshot_venv_lock.sh — spot-check only."
  echo "# Regenerate after pip install + verify_hf_conditioning.py --gpu passes."
  date -u +"# UTC %Y-%m-%dT%H:%M:%SZ"
  for p in "${pkgs[@]}"; do
    ver="$("$PIP" show "$p" 2>/dev/null | awk -F': ' '/^Version:/{print $2}')"
    [[ -n "$ver" ]] && echo "${p}==${ver}"
  done
} > "$OUT"
echo "Wrote $OUT"
cat "$OUT"
